"""
Libri2Mix Dataset Loader for GTCRN_SS Speech Separation.

Aligned with the TFACM open-source data behavior for 2-speaker audio-only
experiments:
  1. Fixed Mixing only
  2. Optional random fixed-length cropping for training
  3. Optional `key` return for evaluation/metric tracking

Libri2Mix directory structure expected:
    Libri2Mix/wav16k/min/
    ├── train-100/
    │   ├── mix_clean/    # mixture wav files (s1 + s2)
    │   ├── s1/           # source 1 wav files
    │   └── s2/           # source 2 wav files
    ├── dev/
    │   ├── mix_clean/
    │   ├── s1/
    │   └── s2/
    └── test/
        ├── mix_clean/
        ├── s1/
        └── s2/

All wav files share the same filename across mix_clean, s1, s2.
Generated by: https://github.com/JorisCos/LibriMix

Reference:
    TFACM repo uses LibriMix train-100, 8kHz, 3-second segments.
"""
import os
import numpy as np
import soundfile as sf
import torch
from torch.utils.data import Dataset
from typing import Optional, List, Tuple


class Libri2MixDataset(Dataset):
    """
    Dataset for Libri2Mix speech separation.
    
    Args:
        data_dir: Path to split directory, e.g. 
                  /path/to/Libri2Mix/wav16k/min/train-100
        sample_rate: Expected sample rate (default: 8000)
        segment: Segment length in seconds (None for full audio)
        num_sources: Number of sources (default: 2)
        mix_type: Mixture type: 'mix_clean' or 'mix_both' (default: 'mix_clean')
        normalize: Whether to normalize audio (default: False)
        random_start: Randomly crop segmented training examples when True
        return_key: Whether to also return the utterance filename key
    """
    def __init__(
        self,
        data_dir: str,
        sample_rate: int = 8000,
        segment: Optional[float] = 3.0,
        num_sources: int = 2,
        mix_type: str = 'mix_clean',
        normalize: bool = False,
        dynamic_mixing: bool = False,
        snr_min: float = -5.0,
        snr_max: float = 5.0,
        random_start: bool = False,
        drop_short_samples: bool = True,
        return_key: bool = False,
    ):
        super().__init__()
        self.data_dir = data_dir
        self.sample_rate = sample_rate
        self.num_sources = num_sources
        self.mix_type = mix_type
        self.normalize = normalize
        self.dynamic_mixing = False
        self.random_start = random_start
        self.drop_short_samples = drop_short_samples
        self.return_key = return_key
        self.eps = 1e-8

        if dynamic_mixing:
            raise ValueError(
                "dynamic_mixing is no longer supported in Libri2MixDataset. "
                "Use fixed mixing to stay aligned with TFACM repo behavior."
            )
        
        # Calculate segment length in samples
        if segment is not None:
            self.seg_len = int(segment * sample_rate)
        else:
            self.seg_len = None
        
        self.is_test = self.seg_len is None
        self._init_fixed_mixing()
    
    def _init_fixed_mixing(self):
        """Initialize for fixed mixing mode (standard Libri2Mix)."""
        # Discover wav files from mix directory
        mix_dir = os.path.join(self.data_dir, self.mix_type)
        if not os.path.isdir(mix_dir):
            raise FileNotFoundError(
                f"Mix directory not found: {mix_dir}\n"
                f"Available: {os.listdir(self.data_dir) if os.path.isdir(self.data_dir) else 'N/A'}"
            )
        
        # Get sorted list of wav files
        self.file_list = sorted([
            f for f in os.listdir(mix_dir) 
            if f.endswith('.wav')
        ])
        
        if len(self.file_list) == 0:
            raise RuntimeError(f"No .wav files found in {mix_dir}")
        
        # Verify source directories exist
        for i in range(1, self.num_sources + 1):
            src_dir = os.path.join(self.data_dir, f's{i}')
            if not os.path.isdir(src_dir):
                raise FileNotFoundError(f"Source directory not found: {src_dir}")
        
        # Pre-compute audio lengths for segment filtering
        self.lengths = []
        for fname in self.file_list:
            info = sf.info(os.path.join(mix_dir, fname))
            self.lengths.append(int(info.frames))
        
        # Filter short samples
        if self.seg_len is not None and self.drop_short_samples:
            self._filter_short_samples()
        elif self.seg_len is not None and not self.drop_short_samples:
            print(
                f"[Libri2MixDataset] Keeping short samples (segment={self.seg_len/self.sample_rate:.1f}s, "
                "drop_short_samples=False)"
            )
        
        print(f"[Libri2MixDataset] Fixed mixing: {len(self.file_list)} samples from {self.data_dir}")
        if self.seg_len is not None:
            print(f"[Libri2MixDataset] Segment: {self.seg_len/self.sample_rate:.1f}s = {self.seg_len} samples")
    
    def _filter_short_samples(self):
        """Remove samples shorter than segment length."""
        orig_len = len(self.file_list)
        filtered_files = []
        filtered_lengths = []
        
        for fname, length in zip(self.file_list, self.lengths):
            if length >= self.seg_len:
                filtered_files.append(fname)
                filtered_lengths.append(length)
        
        drop_count = orig_len - len(filtered_files)
        if drop_count > 0:
            print(f"[Libri2MixDataset] Dropped {drop_count}/{orig_len} samples "
                  f"(shorter than {self.seg_len} samples = {self.seg_len/self.sample_rate:.1f}s)")
        
        self.file_list = filtered_files
        self.lengths = filtered_lengths
    
    def __len__(self) -> int:
        return len(self.file_list)
    
    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, ...]:
        """
        Returns:
            mix: (L,) mixed audio
            sources: (num_sources, L) source audios
        """
        return self._getitem_fixed(idx)
    
    def _getitem_fixed(self, idx: int) -> Tuple[torch.Tensor, ...]:
        """Standard mode: load pre-mixed audio from Libri2Mix files."""
        fname = self.file_list[idx]
        audio_len = self.lengths[idx]
        
        # TIGER-style training uses a random fixed-length crop. Validation and
        # test pass segment=None and therefore keep the complete utterance.
        if self.seg_len is None:
            rand_start = 0
            stop = None
        elif audio_len == self.seg_len:
            rand_start = 0
            stop = None
        elif self.random_start:
            rand_start = np.random.randint(0, audio_len - self.seg_len + 1)
            stop = rand_start + self.seg_len
        else:
            rand_start = 0
            stop = rand_start + self.seg_len
        
        # Load mixture
        mix_path = os.path.join(self.data_dir, self.mix_type, fname)
        mix, _ = sf.read(mix_path, start=rand_start, stop=stop, dtype="float32")
        mix = torch.from_numpy(mix)
        
        # Load sources
        source_list = []
        for i in range(1, self.num_sources + 1):
            src_path = os.path.join(self.data_dir, f's{i}', fname)
            s, _ = sf.read(src_path, start=rand_start, stop=stop, dtype="float32")
            source_list.append(s)
        
        sources = torch.from_numpy(np.stack(source_list, axis=0))  # (num_sources, L)
        
        # Normalize if needed
        if self.normalize:
            mix_std = mix.std(keepdim=True)
            mix = (mix - mix.mean(keepdim=True)) / (mix_std + self.eps)
            sources = (sources - sources.mean(dim=-1, keepdim=True)) / (mix_std + self.eps)
        
        if self.return_key:
            return mix, sources, fname
        return mix, sources
    
    @staticmethod
    def collate_fn(batch: List[Tuple[torch.Tensor, ...]]) -> Tuple[torch.Tensor, ...]:
        """
        Custom collate function for variable-length audio (test mode).
        For training, audio lengths should be the same (segment-based).
        """
        if len(batch[0]) == 3:
            mixes, sources, keys = zip(*batch)
        else:
            mixes, sources = zip(*batch)
            keys = None
        
        lengths = [m.shape[0] for m in mixes]
        if len(set(lengths)) == 1:
            mixes = torch.stack(mixes, dim=0)
            sources = torch.stack(sources, dim=0)
        else:
            max_len = max(lengths)
            padded_mixes = []
            padded_sources = []
            for m, s in zip(mixes, sources):
                pad_len = max_len - m.shape[0]
                if pad_len > 0:
                    m = torch.nn.functional.pad(m, (0, pad_len))
                    s = torch.nn.functional.pad(s, (0, pad_len))
                padded_mixes.append(m)
                padded_sources.append(s)
            mixes = torch.stack(padded_mixes, dim=0)
            sources = torch.stack(padded_sources, dim=0)
        
        if keys is not None:
            return mixes, sources, list(keys)
        return mixes, sources

    @staticmethod
    def collate_fn_with_lengths(
        batch: List[Tuple[torch.Tensor, ...]],
    ) -> Tuple[torch.Tensor, ...]:
        """Preserve true sample counts alongside the padded batch."""

        lengths = torch.tensor([item[0].shape[0] for item in batch], dtype=torch.long)
        collated = Libri2MixDataset.collate_fn(batch)
        if len(collated) == 3:
            mixes, sources, keys = collated
            return mixes, sources, lengths, keys
        mixes, sources = collated
        return mixes, sources, lengths


if __name__ == "__main__":
    print("Libri2MixDataset module loaded successfully.")
    print("\nSupported modes:")
    print("  1. Fixed mixing only")
    print("\nExpected directory structure:")
    print("  Libri2Mix/wav16k/min/train-100/")
    print("  ├── mix_clean/  (mixture wavs)")
    print("  ├── s1/         (source 1 wavs)")
    print("  └── s2/         (source 2 wavs)")
    print("\nGenerate with: ./prepare_libri2mix.sh /path/to/storage")
